version: '3.7'
services:
  db:
    image: mariadb:latest
    # restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: test-db
      MYSQL_USER: masqomar21
      MYSQL_PASSWORD: da21
      MYSQL_TCP_PORT: 3306
  phpmyadmin:
    links:
      - db:db
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_USER: masqomar21
      MYSQL_PASSWORD: da21
      MYSQL_ROOT_PASSWORD: root
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      

volumes:
  mysql_data: